### ISSUE TITLE
Use better exception handling

### ISSUE THREAD

**Issue by tsimonq2** [Debian/britney2#13]
Sometimes the user might forget a file, `data/yakkety/state/age-policy-dates` for example. Instead of throwing `FileNotFoundError` and just freezing (I can `Ctrl + C` of course), it should create the file.

Exception handling should be better integrated so this type of error is less likely to ever happen.

**Comment by nthykier** [comment]
Hi,

Thanks for the report.

I am surprised to hear that Britney freezes (rather than terminating)?

I see no issue with creating the "dates" file automatically.  However, I am concerned with generating the urgencies files as it creates a "silent failure" mode for them (where the intended urgencies do not have an effect).
